name: Run Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: yext/slapshot-reusable-workflows/.github/workflows/run-linting.yml@run_linting