name: Sync Main to Storybook Site Branch

on:
  push:
    branches:
      - main
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.repository.default_branch }}"
          destination_branch: "storybook-site"
          pr_title: "Merge ${{ github.event.repository.default_branch }} into storybook-site"
          pr_body: "Merge ${{ github.event.repository.default_branch }} into storybook-site"
          github_token: ${{ secrets.GITHUB_TOKEN }}
